config/routes.rb
Rails.application.routes.draw do
  resources :trends do 
    collection { post :import }
  end

  root 'welcome#index'

end

app/models/trend.rb
class Trend < ActiveRecord::Base
	def self.import(file)
	    CSV.foreach(file.path, headers: true) do |row|
	      Trend.create! row.to_hash
		end
	end
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
	# include Elasticsearch::Model
	# include Elasticsearch::Model::Callbacks
	Welcome.create title: 'Quick brown fox'
	Welcome.create title: 'Fast black dogs'
	Welcome.create title: 'Swift green frogs'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  before_action :set_trend, only: [:show, :edit, :update, :destroy]

  # GET /trends
  # GET /trends.json
  def index
    @trends = Trend.all
  end

  # GET /trends/1
  # GET /trends/1.json
  def show
  end

  # GET /trends/new
  def new
    @trend = Trend.new
  end

  # GET /trends/1/edit
  def edit
  end

  # POST /trends
  # POST /trends.json
  def create
    @trend = Trend.new(trend_params)

    respond_to do |format|
      if @trend.save
        format.html { redirect_to @trend, notice: 'Trend was successfully created.' }
        format.json { render :show, status: :created, location: @trend }
      else
        format.html { render :new }
        format.json { render json: @trend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trends/1
  # PATCH/PUT /trends/1.json
  def update
    respond_to do |format|
      if @trend.update(trend_params)
        format.html { redirect_to @trend, notice: 'Trend was successfully updated.' }
        format.json { render :show, status: :ok, location: @trend }
      else
        format.html { render :edit }
        format.json { render json: @trend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trends/1
  # DELETE /trends/1.json
  def destroy
    @trend.destroy
    respond_to do |format|
      format.html { redirect_to trends_url, notice: 'Trend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Trend.import(params[:file])
    redirect_to trends_path, notice: "Trend Added Successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trend
      @trend = Trend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trend_params
      params.require(:trend).permit(:country, :product, :strength, :marketshare, :volume, :dashboard)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.require(:welcome).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Merck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trends/_form.html.erb
<%= form_for(@trend) do |f| %>
  <% if @trend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trend.errors.count, "error") %> prohibited this trend from being saved:</h2>

      <ul>
      <% @trend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :strength %><br>
    <%= f.text_field :strength %>
  </div>
  <div class="field">
    <%= f.label :marketshare %><br>
    <%= f.check_box :marketshare %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.check_box :volume %>
  </div>
  <div class="field">
    <%= f.label :dashboard %><br>
    <%= f.text_field :dashboard %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trends/edit.html.erb
<h1>Editing Trend</h1>

<%= render 'form' %>

<%= link_to 'Show', @trend %> |
<%= link_to 'Back', trends_path %>

app/views/trends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merck Trendbreak Dashboard Portal</h1>

<div id="menu">
<nav>
<ul>
<li>Themis</li>
<li>Xponent</li>
<li>Truven</li>
<li>Cerner</li>
<li>GE</li>
</ul>
</nav>
</div>
<table>

  <thead>
    <tr>
      <th>Country</th>
      <th>Product</th>
      <th>Strength</th>
      <th>Marketshare</th>
      <th>Volume</th>
      <th>Dashboard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trends.each do |trend| %>
      <tr>
        <td><%= trend.country %></td>
        <td><%= trend.product %></td>
        <td><%= trend.strength %></td>
        <td><%= trend.cp_marketshare %></td>
        <td><%= trend.cp_volume %></td>
        <td><%= trend.dashboard %></td>
       <!--  <td><%= link_to 'Show', trend %></td>
        <td><%= link_to 'Edit', edit_trend_path(trend) %></td>
        <td><%= link_to 'Destroy', trend, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3>Import Trends</h3>
<%= form_tag import_trends_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Trends" %>
<% end %> 
<!-- 
<%= link_to 'New Trend', new_trend_path %> -->

app/views/trends/new.html.erb
<h1>New Trend</h1>

<%= render 'form' %>

<%= link_to 'Back', trends_path %>

app/views/trends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country:</strong>
  <%= @trend.country %>
</p>

<p>
  <strong>Product:</strong>
  <%= @trend.product %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @trend.strength %>
</p>

<p>
  <strong>Marketshare:</strong>
  <%= @trend.marketshare %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @trend.volume %>
</p>

<p>
  <strong>Dashboard:</strong>
  <%= @trend.dashboard %>
</p>

<%= link_to 'Edit', edit_trend_path(@trend) %> |
<%= link_to 'Back', trends_path %>

app/views/welcome/index.html.erb
<h1>I'm at the welcome page</h1>

app/views/welcomes/_form.html.erb
<%= form_for(@welcome) do |f| %>
  <% if @welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% @welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merck Trendbreak Dashboard Portal</h1>

<table>
  <thead>
  
    <tr>
      <th>Themis</th>
      <th>Xponent</th>
      <th>Truven</th>
      <th>Cerner</th>
      <th>GE</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @welcomes.each do |welcome| %>
      <tr>
        <td><%= welcome.title %></td>
        <td><%= welcome.description %></td>
        <td><%= link_to 'Show', welcome %></td>
        <td><%= link_to 'Edit', edit_welcome_path(welcome) %></td>
        <td><%= link_to 'Destroy', welcome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table class="issuetable">
  <tr>
    <th>Cohort Description</th>
    <th>Market Share</th>
    <th>Sales Volume</th>
    <th>Dashboard</th>
    </tr>
    <tr>
    <td>Insulin 600 mg</td>
    <td><input type="checkbox"></td>
    <td><input type="checkbox"></td>
    <td><a href="http://localhost:5601/app/kibana#/dashboard/timeseries_dashboard1?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'test1_themis_analyzed*',key:product_name,negate:!f,value:insulin),query:(match:(product_name:(query:insulin,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'test1_themis_analyzed*',key:strength,negate:!f,value:'600mg'),query:(match:(strength:(query:'600mg',type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:volume_timeseries,panelIndex:1,row:1,size_x:12,size_y:4,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:timeseries_dashboard1,uiState:())">link to dashboard</a></td>
    </tr>
    <tr>
    <td>Insulin 300 mg</td>
    <td><input type="checkbox"></td>
    <td><input type="checkbox"></td>
    <td><a href="http://localhost:5601/app/kibana#/dashboard/timeseries_dashboard1?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'test1_themis_analyzed*',key:product_name,negate:!f,value:insulin),query:(match:(product_name:(query:insulin,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'test1_themis_analyzed*',key:strength,negate:!f,value:'300mg'),query:(match:(strength:(query:'300mg',type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:volume_timeseries,panelIndex:1,row:1,size_x:12,size_y:4,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:timeseries_dashboard1,uiState:())">link to dashboard</a></td>
    </tr>
    <tr>
    <td>Metformin 300 mg</td>
    <td><input type="checkbox"></td>
    <td><input type="checkbox"></td>
    <td><a href="http://localhost:5601/app/kibana#/dashboard/timeseries_dashboard1?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'test1_themis_analyzed*',key:product_name,negate:!f,value:metformin),query:(match:(product_name:(query:metformin,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'test1_themis_analyzed*',key:strength,negate:!f,value:'300mg'),query:(match:(strength:(query:'300mg',type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:volume_timeseries,panelIndex:1,row:1,size_x:12,size_y:4,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:timeseries_dashboard1,uiState:())">link to dashboard</a></td>
    </tr>
    <tr>
    <td>Metformin 600 mg</td>
    <td><input type="checkbox"></td>
    <td><input type="checkbox"></td>
    <td><a href="http://localhost:5601/app/kibana#/dashboard/timeseries_dashboard1?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'test1_themis_analyzed*',key:product_name,negate:!f,value:metformin),query:(match:(product_name:(query:metformin,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'test1_themis_analyzed*',key:strength,negate:!f,value:'600mg'),query:(match:(strength:(query:'600mg',type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:volume_timeseries,panelIndex:1,row:1,size_x:12,size_y:4,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:timeseries_dashboard1,uiState:())">link to dashboard</a></td>
    </tr>
    <tr>
    <td>Januvia 600 mg</td>
    <td><input type="checkbox"></td>
    <td><input type="checkbox"></td>
    <td><a href="http://localhost:5601/app/kibana#/dashboard/timeseries_dashboard1?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'test1_themis_analyzed*',key:product_name,negate:!f,value:januvia),query:(match:(product_name:(query:januvia,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'test1_themis_analyzed*',key:strength,negate:!f,value:'600mg'),query:(match:(strength:(query:'600mg',type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:volume_timeseries,panelIndex:1,row:1,size_x:12,size_y:4,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:timeseries_dashboard1,uiState:())">link to dashboard</a></td>
    <tr>
    <td>...</td>
    <td><input type="checkbox"></td>
    <td><input type="checkbox"></td>
    <td>link to dashboard</td>
    </tr>



     <th colspan="3"></th>
  </tr>
 
  
</table>




<br>

<%= link_to 'New', new_welcome_path %>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form' %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @welcome.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @welcome.description %>
</p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>